# Generated by Django 3.0.4 on 2020-04-02 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200402_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userportfolio',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_user', to='core.Security'),
        ),
        migrations.AlterField(
            model_name='userportfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_security', to='core.User'),
        ),
    ]
